// built-in docs (src/docs.txt): hover, completion, `mpp doc`, docs/stdlib.md
use std::sync::OnceLock;

pub struct Entry {
    pub section: &'static str,
    pub name: &'static str,
    pub signature: &'static str,
    pub doc: &'static str,
}

const TEXT: &str = include_str!("docs.txt");

pub fn all() -> &'static [Entry] {
    static E: OnceLock<Vec<Entry>> = OnceLock::new();
    E.get_or_init(|| {
        let mut out = Vec::new();
        let mut section = "";
        let mut lines = TEXT.lines().peekable();
        while let Some(l) = lines.next() {
            if let Some(s) = l.strip_prefix("## ") {
                section = s.trim();
                continue;
            }
            if l.trim().is_empty() || l.starts_with(' ') {
                continue;
            }
            let name = l.split(['(', ' ']).next().unwrap_or(l);
            let doc = lines.next_if(|n| n.starts_with("  ")).map_or("", |d| d.trim());
            out.push(Entry { section, name, signature: l.trim(), doc });
        }
        out
    })
}

pub fn find(section: &str, name: &str) -> Option<&'static Entry> {
    all().iter().find(|e| e.section == section && e.name == name)
}

pub fn section(section: &str) -> impl Iterator<Item = &'static Entry> {
    all().iter().filter(move |e| e.section == section)
}

// "stats.ttest", "print", "list.append" or "ttest" (searches everywhere)
pub fn lookup(q: &str) -> Vec<&'static Entry> {
    match q.split_once('.') {
        Some((s, n)) => {
            let sec = if crate::stdlib::is_module(s) { s.to_string() } else { format!("methods {s}") };
            find(&sec, n).into_iter().collect()
        }
        None => {
            let pre: Vec<&Entry> = find("prelude", q).into_iter().collect();
            if !pre.is_empty() { pre } else { all().iter().filter(|e| e.name == q).collect() }
        }
    }
}

// title for a section in docs
fn heading(sec: &str) -> String {
    match sec {
        "prelude" => "Built-in functions (no import needed)".into(),
        s if s.starts_with("methods ") => format!("Methods of `{}`", &s[8..]),
        s => format!("Module `{s}`"),
    }
}

pub fn markdown() -> String {
    let mut o = String::from("# Muaz++ standard library\n\n<!-- generated by `mpp doc --markdown`; edit src/docs.txt instead -->\n\n");
    let mut secs: Vec<&str> = Vec::new();
    for e in all() {
        if !secs.contains(&e.section) {
            secs.push(e.section);
        }
    }
    for s in &secs {
        let anchor = s.replace(' ', "-");
        o.push_str(&format!("- [{}](#{anchor})\n", heading(s)));
    }
    for s in secs {
        o.push_str(&format!("\n<a id=\"{}\"></a>\n## {}\n\n", s.replace(' ', "-"), heading(s)));
        if crate::stdlib::is_module(s) {
            o.push_str(&format!("`import {s}`\n\n"));
        }
        o.push_str("| Function | What it does |\n|---|---|\n");
        for e in section(s) {
            let sig = if crate::stdlib::is_module(s) { format!("{s}.{}", e.signature) } else { e.signature.to_string() };
            o.push_str(&format!("| `{}` | {} |\n", sig.replace('|', "\\|"), e.doc.replace('|', "\\|")));
        }
    }
    o
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::stdlib;

    fn check(section: &str, names: &[&str], bad: &mut Vec<String>) {
        for n in names {
            if find(section, n).is_none() {
                bad.push(format!("missing docs: [{section}] {n}"));
            }
        }
        for e in super::section(section) {
            if !names.contains(&e.name) {
                bad.push(format!("docs for something that does not exist: [{section}] {}", e.name));
            }
        }
    }

    #[test]
    fn every_builtin_is_documented() {
        let mut bad = Vec::new();
        let pre: Vec<&str> = stdlib::BUILTINS.iter().map(|b| b.name).collect();
        check("prelude", &pre, &mut bad);
        for m in stdlib::MODULES {
            let members = stdlib::module(m).unwrap();
            let names: Vec<&str> = members.keys().map(|k| &**k).collect();
            check(m, &names, &mut bad);
        }
        check("methods str", stdlib::str::METHODS, &mut bad);
        check("methods list", stdlib::list::METHODS, &mut bad);
        check("methods map", stdlib::map::METHODS, &mut bad);
        check("methods range", stdlib::RANGE_METHODS, &mut bad);
        check("methods vec", stdlib::vec::METHODS, &mut bad);
        check("methods table", stdlib::table::METHODS, &mut bad);
        check("methods generator", stdlib::generators::METHODS, &mut bad);
        check("methods bandit", stdlib::bandit::METHODS, &mut bad);
        check("methods model", stdlib::llm::MODEL_METHODS, &mut bad);
        check("methods train_log", stdlib::llm::train::METHODS, &mut bad);
        check("methods chart", stdlib::chart::METHODS, &mut bad);
        assert!(bad.is_empty(), "{}", bad.join("\n"));
        assert!(all().iter().all(|e| !e.doc.is_empty()), "every entry needs a description line");
    }

    #[test]
    fn stdlib_md_is_current() {
        let want = markdown();
        let have = std::fs::read_to_string("docs/stdlib.md").unwrap_or_default();
        assert!(have == want, "docs/stdlib.md is stale: run `cargo run -- doc --markdown > docs/stdlib.md`");
    }
}
